import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import PeerComponent from '../components/PeerComponent'
import PeerComponentJoin from '../components/PeerComponentJoin'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // Get peerid from url args
  let urlParams;
  if(typeof window !== "undefined"){
    urlParams = new URLSearchParams(window?.location.search);
  }
  const peerID = urlParams?.get('peerid');

  return (
    <>
      <Head>
        <title>PeerJS Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main className={styles.main}>
      <h1 className={styles.code}>Peerjs Test</h1>
      <PeerComponent/>
      <PeerComponentJoin peerID={peerID || undefined}/>
     </main>
    </>
  )
}
