import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import PeerComponent from "../components/PeerComponent";
import { useHostPeerSession } from "@thebigsasha/react-peerjs-hooks";
import { getJoinURL } from "../utils/getJoinURL";
import { StateInterface, defaultState } from "../utils/sharedState";
import Link from "next/link";
import { FaRegCopy } from "react-icons/fa";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // Get peerid from url args

  const [partnerState, myState, setMyState, isConnected, myID] =
    useHostPeerSession<StateInterface>({
      ...defaultState,
      message: "Hi I'm hosting",
      color: "#00e5ff",
    });

  return (
    <>
      <Head>
        <title>PeerJS Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.code}>Peerjs Test (hosting)</h1>
        <div>
          <div className={styles.card}>
            {!myID && <p>Loading...</p>}
            {/**@ts-ignore*/}
            {myID && (
              <label>
                Join link{" "}
                <a className={styles.code}>
                  {myID}
                </a>
                <FaRegCopy size={15} style={{marginLeft: 5}} onClick={() => navigator.clipboard.writeText(getJoinURL(myID, true))}/>
              </label>
            )}
          </div>
          <PeerComponent
            partnerState={partnerState}
            myState={myState}
            setMyState={setMyState}
            isConnected={isConnected}
          />
        </div>
        <Link href="/join">Join Existing Session</Link>
      </main>
    </>
  );
}
