import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import PeerComponent, { StateInterface } from '../components/PeerComponent'
import { useHostPeerSession, useJoinPeerSession } from '../hooks/usePeer'
import { getJoinURL } from '../utils/getJoinURL';
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // Get peerid from url args
  let peerIDInit = "";

  if(typeof window !== "undefined") {
    const urlParams = new URLSearchParams(window.location.search);
    peerIDInit = urlParams.get('peerid') || "";
  }

  const [peerID, setPeerID] = useState<string>(peerIDInit)
  
  const [partnerState, myState, setMyState, isConnected] = useJoinPeerSession<StateInterface>(peerID, {message: "Hello World", color: "rgb(255,255,100)"})


  return (
    <>
      <Head>
        <title>PeerJS Test - Join</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main className={styles.main}>
      <h1 className={styles.code}>Peerjs Test (joining)</h1>
      <div className={styles.description}>

      <label className={styles.card}>Peer ID <input type="text" value={peerID} onChange={(e) => setPeerID(e.target.value)}/></label>
    <PeerComponent partnerState={partnerState} myState={myState} setMyState={setMyState} isConnected={isConnected}/>
    </div>
    <a href="/">Host</a>
     </main>
    </>
  )
}
